repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml


- repo: local
  hooks:
    - id: ty-check
      name: Run ty type checker
      entry: uv run ty check
      language: system
      types: [python]
      pass_filenames: false  # ty does not need filenames as arguments

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.7
  hooks:
    - id: ruff # Run the linter

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
